version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy

hooks:
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/health_check.sh
      timeout: 60
      runas: ec2-user