server:
  port: 8080
  forward-headers-strategy: native
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  config:
    import: optional:file:dev.env[.properties]
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
  application:
    name: pinpung
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
kakao:
  logout_redirect_uri: ${LOGOUT_REDIRECT_URI}
# Actuator 설정 추가
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: /home/ec2-user/app.log
  level:
    org.springframework:
      boot.actuate.endpoint.web.servlet: TRACE
      security: DEBUG
fastapi:
  server:
    url: http://0.0.0.0:8000